package raft

import (
	"context"
	"net"
	"raft/proto"

	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
)

// GrpcServerAdapter bridges the RaftServiceServer interface generated by protoc
// to the internal RpcHandler interface used by the Raft node.
type GrpcServerAdapter struct {
	raftpb.UnimplementedRaftServiceServer
	handler RpcHandler
}

func (a *GrpcServerAdapter) RequestVote(ctx context.Context, req *raftpb.RequestVoteArgs) (*raftpb.RequestVoteReply, error) {
	// Convert gRPC types to native Go types
	args := &RequestVoteArgs{
		Term:         int(req.Term),
		CandidateId:  int(req.CandidateId),
		LastLogIndex: int(req.LastLogIndex),
		LastLogTerm:  int(req.LastLogTerm),
	}
	var reply RequestVoteReply

	err := a.handler.HandleRequestVote(args, &reply)
	if err != nil {
		return nil, err
	}

	// Convert native reply to gRPC reply
	return &raftpb.RequestVoteReply{
		Term:        int64(reply.Term),
		VoteGranted: reply.VoteGranted,
	}, nil
}

func (a *GrpcServerAdapter) AppendEntries(ctx context.Context, req *raftpb.AppendEntriesArgs) (*raftpb.AppendEntriesReply, error) {
	// Convert LogEntries
	entries := make([]LogEntry, len(req.Entries))
	for i, e := range req.Entries {
		entries[i] = LogEntry{
			Term:    int(e.Term),
			Command: e.Command, // The Command remains a string which works cleanly with string-based state machine
		}
	}

	args := &AppendEntriesArgs{
		Term:         int(req.Term),
		LeaderId:     int(req.LeaderId),
		PrevLogIndex: int(req.PrevLogIndex),
		PrevLogTerm:  int(req.PrevLogTerm),
		Entries:      entries,
		LeaderCommit: int(req.LeaderCommit),
	}
	var reply AppendEntriesReply

	err := a.handler.HandleAppendEntries(args, &reply)
	if err != nil {
		return nil, err
	}

	return &raftpb.AppendEntriesReply{
		Term:    int64(reply.Term),
		Success: reply.Success,
	}, nil
}

type GrpcTransport struct {
	addr     string
	listener net.Listener
}

func NewGrpcTransport(addr string) *GrpcTransport {
	return &GrpcTransport{addr: addr}
}

func (t *GrpcTransport) ListenAndServe(handler RpcHandler) error {
	l, err := net.Listen("tcp", t.addr)
	if err != nil {
		return err
	}
	t.listener = l

	grpcServer := grpc.NewServer()
	adapter := &GrpcServerAdapter{handler: handler}
	raftpb.RegisterRaftServiceServer(grpcServer, adapter)

	// Start accepting connections
	return grpcServer.Serve(t.listener)
}

func (t *GrpcTransport) SendRequestVote(targetAddr string, args *RequestVoteArgs) (*RequestVoteReply, error) {
	// Add WithTransportCredentials(insecure.NewCredentials()) to disable TLS for local testing
	conn, err := grpc.NewClient(targetAddr, grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		return nil, err
	}
	defer conn.Close()

	client := raftpb.NewRaftServiceClient(conn)

	req := &raftpb.RequestVoteArgs{
		Term:         int64(args.Term),
		CandidateId:  int64(args.CandidateId),
		LastLogIndex: int64(args.LastLogIndex),
		LastLogTerm:  int64(args.LastLogTerm),
	}

	res, err := client.RequestVote(context.Background(), req)
	if err != nil {
		return nil, err
	}

	return &RequestVoteReply{
		Term:        int(res.Term),
		VoteGranted: res.VoteGranted,
	}, nil
}

func (t *GrpcTransport) SendAppendEntries(targetAddr string, args *AppendEntriesArgs) (*AppendEntriesReply, error) {
	conn, err := grpc.NewClient(targetAddr, grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		return nil, err
	}
	defer conn.Close()

	client := raftpb.NewRaftServiceClient(conn)

	entries := make([]*raftpb.LogEntry, len(args.Entries))
	for i, e := range args.Entries {
		// e.Command is interface{}, assuming it's a string based on runApplier
		cmdStr, _ := e.Command.(string)
		entries[i] = &raftpb.LogEntry{
			Term:    int64(e.Term),
			Command: cmdStr,
		}
	}

	req := &raftpb.AppendEntriesArgs{
		Term:         int64(args.Term),
		LeaderId:     int64(args.LeaderId),
		PrevLogIndex: int64(args.PrevLogIndex),
		PrevLogTerm:  int64(args.PrevLogTerm),
		Entries:      entries,
		LeaderCommit: int64(args.LeaderCommit),
	}

	res, err := client.AppendEntries(context.Background(), req)
	if err != nil {
		return nil, err
	}

	return &AppendEntriesReply{
		Term:    int(res.Term),
		Success: res.Success,
	}, nil
}
